services:
  - type: web
    name: skul-main-app
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p logs
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn skul_main_data.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: skul_main_data.settings.production
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
